# Generated by Django 6.0.1 on 2026-01-24 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_link_token',
            field=models.CharField(blank=True, help_text='Токен для привязки Telegram аккаунта', max_length=64, null=True, unique=True, verbose_name='Telegram Link Token'),
        ),
    ]
