# Generated by Django 6.0 on 2026-02-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_telegram_link_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_notify_all',
            field=models.BooleanField(default=False, help_text='Если True — присылать все отзывы, иначе только негативные', verbose_name='Все уведомления в Telegram'),
        ),
    ]
