# Generated by Django 6.0 on 2025-12-28 00:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='access_token',
            field=models.TextField(blank=True, verbose_name='Access Token'),
        ),
        migrations.AddField(
            model_name='connection',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='connection',
            name='google_account_id',
            field=models.CharField(blank=True, help_text='accounts/{accountId}', max_length=50, verbose_name='Google Account ID'),
        ),
        migrations.AddField(
            model_name='connection',
            name='google_location_id',
            field=models.CharField(blank=True, help_text='locations/{locationId}', max_length=50, verbose_name='Google Location ID'),
        ),
        migrations.AddField(
            model_name='connection',
            name='last_sync_error',
            field=models.TextField(blank=True, verbose_name='Ошибка синхронизации'),
        ),
        migrations.AddField(
            model_name='connection',
            name='last_sync_status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('success', 'Успешно'), ('error', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус синхронизации'),
        ),
        migrations.AddField(
            model_name='connection',
            name='refresh_token',
            field=models.TextField(blank=True, verbose_name='Refresh Token'),
        ),
        migrations.AddField(
            model_name='connection',
            name='sync_frequency',
            field=models.PositiveIntegerField(default=3600, help_text='По умолчанию: 1 час', verbose_name='Частота синхронизации (сек)'),
        ),
        migrations.AddField(
            model_name='connection',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Token Expires'),
        ),
        migrations.AddField(
            model_name='connection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
