# Generated by Django 6.0 on 2026-02-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_connection_access_token_connection_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='url_path',
            field=models.CharField(blank=True, help_text='Формат: название/город/улица', max_length=300, null=True, unique=True, verbose_name='URL путь'),
        ),
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='URL (старый)'),
        ),
    ]
