# Generated by Django 6.0 on 2026-02-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_add_url_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='url_path',
        ),
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='URL'),
        ),
    ]
