# Generated by Django 6.0 on 2026-02-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_remove_url_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Демо-компания с примерами отзывов, доступная всем новым пользователям только для просмотра', verbose_name='Демо-компания'),
        ),
    ]
