# Generated by Django 6.0 on 2026-02-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_add_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='analysis_mode',
            field=models.CharField(choices=[('basic', 'Базовый (паттерны)'), ('ai', 'AI-анализ (DeepSeek)')], default='basic', help_text='basic — бесплатные паттерны, ai — DeepSeek + 8 подкатегорий', max_length=10, verbose_name='Режим анализа'),
        ),
    ]
