# Generated by Django 6.0 on 2026-02-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_analysis_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='platform_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Рейтинг на платформе'),
        ),
        migrations.AddField(
            model_name='connection',
            name='platform_review_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Кол-во отзывов на платформе'),
        ),
    ]
