# Generated by Django 6.0 on 2025-12-27 23:24

import apps.qr.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QR',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(default=apps.qr.models.generate_short_code, help_text='Уникальный код для URL (например: ABC12345)', max_length=8, unique=True, verbose_name='Код')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='Цвет')),
                ('background', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Фон')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='qr_logos/', verbose_name='Логотип')),
                ('image', models.ImageField(blank=True, null=True, upload_to='qrcodes/', verbose_name='Изображение QR')),
                ('scans', models.PositiveIntegerField(default=0, verbose_name='Сканирований')),
                ('last_scan_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее сканирование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_codes', to='companies.company', verbose_name='Компания')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('spot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_codes', to='companies.spot', verbose_name='Точка')),
            ],
            options={
                'verbose_name': 'QR-код',
                'verbose_name_plural': 'QR-коды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QRScan',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('scanned_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User Agent')),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='ID сессии')),
                ('qr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='qr.qr', verbose_name='QR-код')),
            ],
            options={
                'verbose_name': 'Сканирование',
                'verbose_name_plural': 'Сканирования',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
