# Generated by Django 6.0 on 2025-12-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='back_color',
            field=models.CharField(default='white', max_length=20, verbose_name='Background Color'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='fill_color',
            field=models.CharField(default='black', max_length=20, verbose_name='Fill Color'),
        ),
    ]
