# Generated by Django 6.0 on 2025-12-27 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode_app', '0002_qrcode_back_color_qrcode_fill_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo'),
        ),
    ]
