# Generated by Django 6.0 on 2025-12-27 23:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('qr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('internal', 'Наш сервис'), ('yandex', 'Яндекс Карты'), ('2gis', '2GIS'), ('google', 'Google Maps'), ('tripadvisor', 'TripAdvisor')], default='internal', max_length=20, verbose_name='Источник')),
                ('external_id', models.CharField(blank=True, max_length=100, verbose_name='ID на платформе')),
                ('external_url', models.URLField(blank=True, max_length=500, verbose_name='Ссылка на отзыв')),
                ('author_name', models.CharField(blank=True, default='Аноним', max_length=100, verbose_name='Имя автора')),
                ('author_contact', models.CharField(blank=True, max_length=200, verbose_name='Контакт')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('text', models.TextField(blank=True, verbose_name='Текст')),
                ('ratings', models.JSONField(blank=True, default=dict, verbose_name='Детальные оценки')),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'Позитивный'), ('neutral', 'Нейтральный'), ('negative', 'Негативный')], max_length=20, verbose_name='Тональность')),
                ('sentiment_score', models.DecimalField(blank=True, decimal_places=2, help_text='-1.00 (негатив) до +1.00 (позитив)', max_digits=3, null=True, verbose_name='Оценка тональности')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Теги')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('resolved', 'Решён'), ('archived', 'Архив')], default='new', max_length=20, verbose_name='Статус')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичный')),
                ('response', models.TextField(blank=True, verbose_name='Ответ')),
                ('response_at', models.DateTimeField(blank=True, null=True, verbose_name='Время ответа')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('platform_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата на платформе')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='companies.company', verbose_name='Компания')),
                ('qr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='qr.qr', verbose_name='QR-код')),
                ('response_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to=settings.AUTH_USER_MODEL, verbose_name='Ответил')),
                ('spot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='companies.spot', verbose_name='Точка')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'source'], name='reviews_rev_company_ff63c5_idx'), models.Index(fields=['company', 'status'], name='reviews_rev_company_8e9cd3_idx'), models.Index(fields=['company', 'rating'], name='reviews_rev_company_9bf8b8_idx')],
            },
        ),
    ]
