# Generated by Django 6.0 on 2025-12-28 19:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_add_photo_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='reviews/%Y/%m/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='reviews.review', verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Фото отзыва',
                'verbose_name_plural': 'Фото отзывов',
                'ordering': ['created_at'],
            },
        ),
    ]
