# Generated by Django 6.0 on 2025-12-30 09:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_add_review_photo_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Отзыв получен'), ('response_sent', 'Ответ отправлен'), ('status_changed', 'Статус изменён'), ('assigned', 'Назначен ответственный'), ('note_added', 'Добавлена заметка')], max_length=20, verbose_name='Действие')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='reviews.review', verbose_name='Отзыв')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История отзыва',
                'verbose_name_plural': 'История отзывов',
                'ordering': ['-created_at'],
            },
        ),
    ]
