# Generated by Django 6.0 on 2026-01-18 16:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_connection_access_token_connection_created_at_and_more'),
        ('qr', '0001_initial'),
        ('reviews', '0004_reviewhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['company', '-created_at'], name='reviews_rev_company_2e4ded_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['company', 'sentiment'], name='reviews_rev_company_292cd3_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['status', '-created_at'], name='reviews_rev_status_70a1f9_idx'),
        ),
    ]
