# Generated by Django 6.0 on 2026-02-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='wants_contact',
            field=models.BooleanField(default=False, help_text='Клиент отметил галочку "Свяжитесь со мной"', verbose_name='Просит связаться'),
        ),
    ]
