# Generated by Django 6.0 on 2026-02-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_add_wants_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='tags_complex',
            field=models.BooleanField(default=False, help_text='Конфликт между рейтингом и sentiment тегов — анализ может быть неточным', verbose_name='Сложный отзыв'),
        ),
    ]
